### ISSUE TITLE
predict needs to calculate the year a given text was created 

### ISSUE THREAD

**Issue by kmunger** [kbenoit/sophistication#3]
in the R package, the predict function first needs to calculate the covariates on the new text

and currently, the google year is hardcoded
```
compute_google_min_2000 <- function(toks) {
   baseline_word <- "the"
   baseline_year <- 2000
```

It needs to be able to take as an argument the year (decade) that a given text was written

**Comment by kmunger** [comment]
@kbenoit Ok we have this now. In playing around, there looks like there's something odd going on with the bootstrapping 

> results<-predict_readability(BT_best, newdata = data_corpus_sotu, bootstrap_n = 10, verbose = T, 
+                              baseline_year = year)
Starting predict_readability (sophistication v0.65)...
   ...using BT_best as fitted BT model; data_corpus_sotu as newdata
   ...tagging parts of speech
   ...computing word lengths in characters
   ...computing baselines from Google frequencies
   ...aggregating to sentence level
   ...recombining bootstrapped sentence-level quantities
   ...computing predicted values
   ...finished; elapsed time: 236 seconds.
Warning message:
In predict_readability.BTm(BT_best, newdata = data_corpus_sotu,  :
  bootstrap_n ignored; only new texts can be bootstrapped
> results$year<-year
> p <- ggplot(data = results) + #, group = delivery)) +
+   theme(panel.grid.major = element_blank(),
+         panel.grid.minor = element_blank(),
+         panel.background = element_blank(),
+         axis.line = element_line(colour = "black")) +
+ theme(legend.position="none", axis.text.x = element_text(size = 15),
+         axis.text.y = element_text(size = 15), axis.title.y = element_text(size = 15))+
+   xlab("") +
+   ylab("Probability SOTU is Easier than a 5th Grade Text") +
+   geom_point(aes(x= year, y = prob),   size = 2, color = "black", shape = 16) +
+   
+   geom_errorbar(aes(ymin = prob_lo, ymax = prob_hi, x = year), width = 0.25)+
+   theme(plot.title = element_text(lineheight=.8, face="bold"))
> print(p)
> results<-predict_readability(BT_best, newdata = data_corpus_sotu, bootstrap_n = 0, verbose = T, 
+                              baseline_year = year)
Starting predict_readability (sophistication v0.65)...
   ...using BT_best as fitted BT model; data_corpus_sotu as newdata
   ...tagging parts of speech
   ...computing word lengths in characters
   ...computing baselines from Google frequencies
   ...aggregating to sentence level
   ...computing predicted values
   ...finished; elapsed time: 226 seconds.

**Comment by kmunger** [comment]
If I specify n_bootstrap  = 10, it does the bootstrapping, but I get a warning saying 

Warning message:
In predict_readability.BTm(BT_best, newdata = data_corpus_sotu, :
bootstrap_n ignored; only new texts can be bootstrapped

and it took 236 seconds.

If I specify n_bootstrap  = 0, it doesn't do the bootstrapping, but it takes nearly as long

**Comment by ArthurSpirling** [comment]
*meta-comment -- shouldn't this be in sophistication-papers?*

**Comment by kbenoit** [comment]
@kmunger dont worry about the message, the behaviour is correct. I will fix that Sunday. Going off line (on Loch Lomond!) until Sunday pm.

The bootstrapping is super fast because it tags every sentence and then resamples the already spacy-ed sentences. All the time is from the tagging.

**Comment by kbenoit** [comment]
@ArthurSpirling we have kept the package and the functions separate from the paper.

**Comment by kmunger** [comment]
ok sounds good!
